# Generated by Django 4.0.3 on 2023-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_clienta', models.IntegerField(verbose_name='Rut')),
                ('dv_clienta', models.CharField(max_length=1, verbose_name='Dv')),
                ('tipo_clienta', models.IntegerField(verbose_name='Tipo de Clienta')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nom_fantasia', models.CharField(max_length=100, verbose_name='Nombre de Fantasia')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('tel', models.IntegerField(verbose_name='Telefono de Contacto')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=10, verbose_name='Datos adicionales a la dirección')),
                ('giro', models.CharField(max_length=200, verbose_name='Giro Empresa')),
            ],
        ),
    ]
