# Generated by Django 4.0.3 on 2023-06-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clienta',
        ),
    ]
